TriggerMail/incubator-airflow

- airflow/contrib/hooks/gcp_dataflow_hook.py
- airflow/contrib/operators/dataflow_operator.py
- airflow/contrib/sensors/gcs_sensor.py
Adding a few cherrypicked Airflow updates.
1. Chen is dealing with the Dataflow Operator and has found the logging to be inefficient/not useful. The newer version of the Dataflow hook will hopefully provide more information.
2. I want to use the newly available GoogleCloudStoragePrefixSensor for Opportunity Finder.
Fingers crossed.
> cherrypick airflow updates;

- airflow/contrib/operators/kubernetes_operator.py
- airflow/contrib/utils/kubernetes_utils.py
- tests/contrib/operators/test_kubernetes_operator.py
move all yaml generation stuff to utils
simplify operator
simplify tests
> refactoring

- airflow/contrib/operators/kubernetes_operator.py
people want to see the logs of their failed jobs
> dont clean up failed jobs

- airflow/contrib/operators/kubernetes_operator.py
will only delete jobs that succeeded
failed jobs will need to be cleaned separately
> fix comment

- airflow/contrib/operators/kubernetes_operator.py
We need to provide this option to communicate the result from one step to another in airflow.
> Add do_xcom_push to kubernetes_operator.py

- airflow/contrib/operators/kubernetes_operator.py
Sometimes, we need to dynamically pass in parameters into commands.
One use case is to pass in through xcom.
> Add support to append extra parameters

- airflow/logging_config.py
need to know why this is failing
> add error message

- airflow/contrib/operators/kubernetes_operator.py
I should be able to log from KubernetesJobOperator...
> try logging from worker

- airflow/contrib/operators/kubernetes_operator.py
> try self.log.info to see if that's what's working

- airflow/contrib/operators/kubernetes_operator.py
> remove return

- airflow/contrib/operators/kubernetes_operator.py
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L165
> validating container names in the initializer of KubernetesJobOperator

- airflow/contrib/operators/kubernetes_operator.py
this ensures that the container logs will still be captured on failure (which is when you need logs most)
> still log on failure

- airflow/contrib/operators/kubernetes_operator.py
* Reading all pods related to the job
* Looking to see if any independent containers are still running
* If not, consider the pod complete
* `finally` block in `poll_job_completion` to stop any dependent containers still running
https://bluecore.atlassian.net/browse/PROD-11881
> Preventing dependent containers from keeping pods running in KubernetesJobOperator

- airflow/contrib/operators/kubernetes_operator.py
* Using `pod_output = get_pods(<jobname>)` to enumerate pods/containers
* Reusing pod_output when possible
* Logging each container separately, line-by-line, with `extra`
* Using pod_output for the xcom_push stuff
https://bluecore.atlassian.net/browse/PROD-11881
> Logging in a multi-container, multi-pod world

- airflow/contrib/operators/kubernetes_operator.py
> using set literal

- airflow/contrib/operators/kubernetes_operator.py
> kubenetes doesn't preserve labels on jobs

- airflow/contrib/operators/kubernetes_operator.py
* Reading AIRFLOW_GOOGLE_CLOUDSQL_PROXY_IMAGE or using default
https://bluecore.atlassian.net/browse/PROD-12017
> Looking in environment variable for cloudsql_proxy image

- airflow/contrib/operators/kubernetes_operator.py
Previously, we were only looking at the status of the pod. However, since the pod won't be marked as succeeded or failed until all the containers stop, the cloud_sql_proxy is preventing the 'failed' status from appearing. Instead, we will look at the individual containers and fail the operation if any of them are in a 'terminated' state with an exit code greater than zero.
> Checking container status

- airflow/contrib/operators/kubernetes_operator.py
> fix pod_output referenced before assignment

- airflow/contrib/operators/kubernetes_operator.py
* Moved the 'clean' operation after we handle logs
* Put the log handling in a try..except block
> Ensuring that we move our logs before we try to clean

- airflow/contrib/operators/kubernetes_operator.py
* Moved the 'clean' operation after we handle logs
* Put the log handling in a try..except block
>  Ensuring that we move our logs before we try to clean

- airflow/utils/log/gcs_task_handler.py
> add logging to gcs to debug dev logs

- airflow/utils/log/gcs_task_handler.py
this should hopefully break something, otherwise the config is wrong
> remove fallback to file task handler

- airflow/utils/log/file_task_handler.py
- airflow/www/views.py
confirm logger, task log reader, and handler are set properly
> add more logging debug logs

- airflow/utils/log/gcs_task_handler.py
will this keep it from going to file task handler?
> try adding read to gcs task handler

- airflow/utils/log/file_task_handler.py
- airflow/utils/log/gcs_task_handler.py
undo debugging changes that didn't work
> Undo add read to gcs task handler

- airflow/contrib/operators/app_engine_operator.py
* New version of AppEngineOperator
* Uses XComs to communicate job status
* Logs additional exception information you get by using the XCom context manager (in trigger_mail)
* Added timeout and max polling interval to existing AppEngineOperator
https://bluecore.atlassian.net/browse/PROD-12149
> AppEngineOperatorV2

- airflow/contrib/hooks/gcp_api_base_hook.py
- airflow/contrib/hooks/gcs_hook.py
* New version of AppEngineOperator
* Uses XComs to communicate job status
* Logs additional exception information you get by using the XCom context manager (in trigger_mail)
* Added timeout and max polling interval to existing AppEngineOperator
https://bluecore.atlassian.net/browse/PROD-12149
>  AppEngineOperatorV2 (dev -> master)

- airflow/contrib/operators/app_engine_operator.py
> support for cloudsql sockets

- airflow/contrib/utils/kubernetes_utils.py
> removing the timestamp from the unique name

- airflow/contrib/operators/kubernetes_operator.py
https://bluecore.atlassian.net/browse/PROD-12285
> Passing the airflow environment (dev, qa, prod) as an environment variable to the instance so we can later pass it to Datadog

- airflow/settings.py
* Previously, the basic statsd client is all you could use in Airflow
* DogStatsd has the added advantage of allowing for tags, which we want
* New code allows for specifying the stats class by (fully-qualified) name
> Dynamically loading the stats class based on a config value

- airflow/settings.py
`statsd.StatsClient` calls it `prefix`, `DogStatsd` calls it `namespace`. This stinks.
> Explicitly handling DogStatsd

- airflow/settings.py
> dev => master

- airflow/contrib/utils/dogstatsd_adapter.py
- airflow/settings.py
Interfaces were different. Done messing around
> Created DogStatsdAdapter to make DogStatsd smell like statsd.StatsClient

- airflow/contrib/operators/app_engine_operator.py
> revised sync and async AppEngineOperator to issue proper post for airflow_handler_v2

- airflow/contrib/operators/app_engine_operator.py
> sending command params directly in sync airflow operator

- airflow/contrib/operators/app_engine_operator.py
> fixing broken import

- airflow/contrib/operators/app_engine_operator.py
I am dumb and don't notice stuff.
> same thing, but this time for async

- airflow/contrib/operators/app_engine_operator.py
> removed accidentally hardcoded config values

- airflow/contrib/operators/app_engine_operator.py
- airflow/contrib/utils/xcom.py
> add new util function to check if XCom has been added to database

- airflow/contrib/operators/app_engine_operator.py
- airflow/contrib/utils/kubernetes_utils.py
- airflow/contrib/utils/parameters.py
@dangermike Are you ready to merge your commits below to master?
>  add new util function to check if XCom has been added to database

- airflow/contrib/operators/app_engine_operator.py
> cleaner loop, more logging

- airflow/contrib/operators/kubernetes_operator.py
Dear Airflow maintainers,
Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!
- https://issues.apache.org/jira/browse/AIRFLOW-XXX
1. Subject is separated from body by a blank line
2. Subject is limited to 50 characters
3. Subject does not end with a period
4. Subject uses the imperative mood ("add", not "adding")
5. Body wraps at 72 characters
6. Body explains "what" and "why", not "how"
> PROD-19007 Change status check to correctly handle pending containers

- airflow/contrib/operators/kubernetes_operator.py
Dear Airflow maintainers,
Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!
- https://issues.apache.org/jira/browse/AIRFLOW-XXX
1. Subject is separated from body by a blank line
2. Subject is limited to 50 characters
3. Subject does not end with a period
4. Subject uses the imperative mood ("add", not "adding")
5. Body wraps at 72 characters
6. Body explains "what" and "why", not "how"
> PROD-19007 remove bad reference

- airflow/contrib/operators/kubernetes_operator.py
Changes:
* PROD-19007 - Poll for container completion in a manner that does not present a race condition for pods that are pending.
> Promote from QA to master

- airflow/contrib/operators/kubernetes_operator.py
- airflow/contrib/utils/bluecore_bq_gcs_task_handler.py
* Print timestamp during logging
* Fixed logging double line spacing weirdness 
* Handling of 400 error when query is empty, usually at the end of a job
> Improvements to Airflow Logging

- airflow/contrib/operators/kubernetes_operator.py
i may have put this in the wrong area but just adding more verbosity around when a job fails to describe the job and also describe the associated pod
for some reason my yapf is showing formatting changes on this so browse with ?w=1
> adding more job/pod verbosity during failures

- airflow/models.py
> Revert "Merge pull request #244 & #242 from TriggerMail/test"

- airflow/contrib/operators/kubernetes_operator.py
- airflow/models.py
Add labels so that airflow job costs can be properly attributed.
> [PROD-24163] Label KJO for billing
