- airflow/contrib/hooks/gcp_dataflow_hook.py
We skip passing in job_name to dataflow in airflow.  Otherwise this will prevent to run multiple jobs inside the airflow job.
> not pass in job_name from airflow

- airflow/contrib/operators/kubernetes_operator.py
Data Science wants to be able to review logs of successful jobs/pods.
To do this, adding a quick flag so people can opt-in to not deleting successful jobs/pods.
Future fix: put logs somewhere better, pull this out.
> flag to clean up/not clean up successful jobs

- airflow/contrib/operators/kubernetes_operator.py
boolean makes yaml validation fail
[2018-05-15 22:30:11,479] {logging_mixin.py:93} INFO - [2018-05-15 22:30:11,478] {base_task_runner.py:98} INFO - Subtask: error: error validating "/tmp/tmpiybipt.yaml": error validating data: expected type string, for field spec.template.spec.containers[0].env[4].value, got bool; if you choose to ignore these errors, turn validation off with --validate=false
> use string not bool

- airflow/contrib/operators/kubernetes_operator.py
we had a temporary workaround to allow jobs/pods to live longer so people could more easily view logs
now that we have logs (in GCS and in web UI), we don't need this anymore
> always clean up pods and jobs

- airflow/bin/cli.py
The cli wrapper `airflow flower` did not support the `flower --auth=<email regex>` parameter required to make OAuth work. This is now supported as `airflow flower --flower_auth=<email regex>`.
> Support for oauth in flower

- airflow/bin/cli.py
- airflow/contrib/hooks/gcp_api_base_hook.py
GUnicorn, by default, expects that proxies will be on the same box. Because we have Google's load balancers terminating TLS, which is off-box, GUnicorn is not respecting the `X-Forwarded-Proto` header. Adding this parameter tells GUnicorn that it should respect `X-Forwarded-Proto` regardless. This is not always good because a malicious client could theoretically downgrade to HTTP. In our case, the fact that Google is terminating TLS for us will prevent a client from doing anything cute -- they can _request_ HTTP, but it won't work.
https://bluecore.atlassian.net/browse/PROD-12041
https://bluecore.atlassian.net/browse/PROD-7793
> Adding `--forwarded-allow-ips *` to the gunicorn invocation

- airflow/contrib/operators/kubernetes_operator.py
we want to store all kubernetes job operator docker images in triggeredmail because it will simplify the moves between dev, qa, and production
this change will default to grabbing images from the triggeredmail container registry if full path to image isn't given
> default to grabbing images from us.gcr.io/triggeredmail

- airflow/contrib/operators/kubernetes_operator.py
* This had been hard-coded for QA
* Reading from the same config just created to send to App Engine
> BUGFIX: Providing a proper instance name for the cloudsql proxy sidecar

- airflow/contrib/operators/app_engine_operator.py
- airflow/models.py
* Cleaned up the interface
* Passes the command and sync state in the URL
* /api/airflow/(sync|async)/<command_name>
* New sync version for short App Engine calls
* POSTs synchronously over HTTP(S)
* If a response is provided, it will be loaded as the `return_value` XCom
* JSON and YAML are deserialized
* text/plain is stored as text
* Other values are stored as binary
* Set XCom to pickle using `HIGHEST_PROTOCOL` because I was way too annoyed
> Created AppEngineOperatorSync, renamed AEOv2 to AppEngineOperatorAsync

- airflow/contrib/operators/kubernetes_operator.py
* Volumes taken in as a list of dictionaries as defined in the [API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#volume-v1-core)
* `airflow-cloudsql-instance-credentials` and the volume for the `service_account_secret` are special and will overwrite provided values
* Volumes specified in yaml for `from_job_yaml` are preserved
https://bluecore.atlassian.net/browse/PROD-12260
> Adding support for caller-specified volumes in KubernetesJobOperator

- airflow/contrib/operators/app_engine_operator.py
* This is required to handle Airflow variables from AppEngine
* See https://cryptography.io/en/latest/fernet/ for details
https://bluecore.atlassian.net/browse/PROD-12320
> Adding Fernet key to AppEngineOperator requests

- airflow/contrib/operators/app_engine_operator.py
Dear Airflow maintainers,
Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!
- https://issues.apache.org/jira/browse/AIRFLOW-XXX
1. Subject is separated from body by a blank line
2. Subject is limited to 50 characters
3. Subject does not end with a period
4. Subject uses the imperative mood ("add", not "adding")
5. Body wraps at 72 characters
6. Body explains "what" and "why", not "how"
> change async operator attribute name to avoid overriding BaseOperator attribute

- airflow/contrib/operators/kubernetes_operator.py
- airflow/contrib/utils/kubernetes_utils.py
- airflow/contrib/utils/statsd_adapter.py
- airflow/jobs.py
- airflow/models.py
- airflow/settings.py
https://bluecore.atlassian.net/browse/PROD-13444
StatsD doesn't support tags, but we really want success/failure stats on a per task or per dag basis. This was accomplished by adding a tag-ignoring wrapper on top the StatsClient. Ironically, we now have the distinction of using a stats interface that matches neither statsd nor dogstatsd.
___NOTE:___ _WE DO NOT SUPPORT STATS IN DEV OR QA, SO THIS CANNOT BE TESTED!_
This isn't used in PROD yet, but is a backwards compatible chain
> Dev -> Master

- airflow/contrib/operators/app_engine_operator.py
This PR makes it possible to pass in task instance variables to appengine operators as command parameters via "macros" and jinja templates: 
https://airflow.readthedocs.io/en/latest/tutorial.html#templating-with-jinja
This means the values we pass a jinja string "template" into `command_params`, and before the task actually operates, it'll render the strings.
Enabling something like:
```
execution_date = "{{ ds }}"
query_task = AppEngineOperatorSync(
task_id='{}_query_task_{}'.format(job_prefix, partner),
command_name='engine.campaign_tools.commands.AirflowParseWidgetProductOpenDataSinglePartner',
command_params={'namespace': partner, 'date': execution_date}
)
```
(`{{ `ds`  }}` is a very commonly used variable)
When you specify `command_params` as a `template_field`, if the value passed …
> Add command params as template field for appengine operators

- airflow/contrib/operators/app_engine_operator.py
put this back in now that we believe we can build/deploy airflow correctly
> Revert "Revert "Add command params as template field for appengine operators""

- setup.py
Pandas 0.24 was released recently, and it no longer has a `tools.merge` module:
https://github.com/pandas-dev/pandas/tree/v0.23.4/pandas
https://github.com/pandas-dev/pandas/tree/v0.24.0/pandas
so we're getting this error for dags with `BigQueryOperators`:
So we need to pin pandas to < .24
I tried to test this fix in the dev environment, but when I create a dag with a BigQueryOperator in dev, circleci seems to not pull from this repository's `dev` branch: https://circleci.com/gh/TriggerMail/airflow-dag/2051?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
though I believe this should work, as the change does successfully bring the pandas version down to .23.4
(screenshot of our dev airflow environment's pip freeze):
I will test deploying this to QA before …
> pin pandas

- airflow/contrib/operators/kubernetes_operator.py
This case occurs when we are retrying after a previous attempt successfully finish execution, killed dependent containers, and failed to delete the job.  In this scenario, we want to immediately stop polling, and retry job deletion.
> Handle case where pod is Succeeded and job is Running

- setup.py
Pin celery version to 4.1.1
source:
https://github.com/celery/celery/issues/3802
> PROD-21235 Pin celery version to avoid known regression tracked in celery/issues/3802

- setup.py
Reverts TriggerMail/incubator-airflow#206 because of:
https://github.com/celery/celery/commit/ec1fd31e9baed79d54c3e36b5f5d37e6e70a246f
> Revert "PROD-21235 Pin celery version to avoid known regression tracked in celery/issues/3802"

- airflow/models.py
In a completely uncharacteristic and disappoing move, MySQL's optimizer fails to make good decisions about index choices. When there are no task IDs provided to the query, it will use `ti_dag_state`, which is highly selective when the state is `running`. We have added a hint. While forcing the index is not a generally safe assumption, the only place `airflow.models.DAG.get_num_task_instances` is called is in airflow.jobs.SchedulerJob._find_executable_task_instances(), which is looking specifically for running states, and `airflow.models.DAG.concurrency_reached` also looks specifically for `running`. The hint should keep the number of inspected rows down to a dull roar.
[sqlalchemy.orm.query.Query.with_hint docs](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.wi …
> Adding hint to status checking queries

- airflow/models.py
- airflow/www/views.py
When a dagrun's state is manually changed to either `success` or `failed` from the `edit` page, task instances that are unfinished do not get transitioned to `failed` or `succeeded`, but rather just get a null state. This clogs up the scheduler when it ticks and delays task runs in the future. Fix that
> [PROD-26871] Kill unfinished tasks when dagrun is manually changed to DagRun.state

- airflow/models.py
Without sharing the same session instance, the UI dagrun would end up being left in state `running`. Fix that
> [PROD 26871] Fix marking tasks as failed

- airflow/www/views.py
When a DagRun is manually marked as {failed, success} in the UI, we want to also update it's tasks because they otherwise clog up the scheduler. This accomplishes that easily explainable, yet very tedious task. 😡
> [PROD-26871] Mark tasks as failed

- airflow/contrib/operators/kubernetes_operator.py
- airflow/models.py
Labels were placed in the wrong place with #249 and we have a lot dags running on a per-partner basis so we should add a `partner` label on the operator level for more labels
> [PROD 24163] & [PROD 27873] fix labels & add `partner` label
